version: '3.3'

services:
  postgres:
    image: "docker-proxy.artifactory.tcsbank.ru/postgres:12.6"
    environment:
      POSTGRES_PASSWORD: '123'
      POSTGRES_USER: 'test'
    ports:
      - 5432:5432

  redis-cluster:
    image: "docker-proxy.artifactory.tcsbank.ru/bitnami/redis-cluster:7.0.10"
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      # Redis Cluster requires at least 3 master nodes.
      REDIS_NODES: redis-cluster redis-cluster redis-cluster
      REDIS_CLUSTER_CREATOR: 'yes'
      REDIS_CLUSTER_REPLICAS: 0
      REDIS_CLUSTER_ANNOUNCE_IP: localhost
      REDIS_CLUSTER_ANNOUNCE_PORT: 6379
      REDIS_CLUSTER_DYNAMIC_IPS: 'no'
